<a href="https://colab.research.google.com/github/mducdaf2/tensorflow/blob/main/2_nn_sequential_funcAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Neural Network with Sequential and Functional API

In [1]:
import os
os.environ["TFF_CPP_MIN_LOG_LEVEL"] = "2"

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [23]:
print(x_train[0].shape)

(784,)


In [4]:
x_train = x_train.reshape(-1, 784)
print(x_train.shape)
print(x_train.dtype)
x_train = x_train.astype("float32") / 255.0
print(x_train.dtype)
x_test = x_test.reshape(-1, 784)
x_test = x_test.astype("float32") / 255.0

(60000, 784)
uint8
float32


In [5]:
# Nếu ở dạng numpy array thì việc chuyển qua tensor là không cần thiết.
x_train = tf.convert_to_tensor(x_train)
print(type(x_train))

<class 'tensorflow.python.framework.ops.EagerTensor'>


## Sequential API
Very convenient, not very flexible.

In [18]:
a = tf.random.normal((10, ))
b = tf.random.normal((10, 1))
c = tf.random.normal((1, 10))
print(a)
print(b)
print(c)

tf.Tensor(
[ 0.8181007  -0.7585225  -0.01933241  0.8293126   1.0320599  -1.6997159
 -0.38450545 -0.06813428 -2.0812573   0.2196438 ], shape=(10,), dtype=float32)
tf.Tensor(
[[ 2.5403755 ]
 [-1.0477664 ]
 [-0.56694204]
 [ 0.92809314]
 [-1.08274   ]
 [ 1.0005325 ]
 [-0.3969506 ]
 [-1.3984015 ]
 [ 1.0449989 ]
 [ 1.0550171 ]], shape=(10, 1), dtype=float32)
tf.Tensor(
[[ 0.00996417 -1.1873131  -1.3811578   0.51211095 -1.2298162  -0.7213515
   0.24910226  0.44944078  0.40364182 -0.6502523 ]], shape=(1, 10), dtype=float32)


In [20]:
model = keras.Sequential([
    keras.Input(shape=(784, )),
    layers.Dense(units=512, activation="relu"),
    layers.Dense(units=256, activation="relu"),
    layers.Dense(10),
])

print(model.summary())

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

None


In [28]:
model = keras.Sequential()
model.add(layers.Input(shape=(784, )))
model.add(layers.Dense(512, "relu"))
model.add(layers.Dense(256, "relu"))
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_21 (Dense)                │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

None


In [29]:
# Compile model: config cấu hình training cho model
model.compile(
    # from_logits=True -> cho output qua softmax trước khi tính loss
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

In [30]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 7s - 4ms/step - accuracy: 0.9419 - loss: 0.1882
Epoch 2/5
1875/1875 - 5s - 3ms/step - accuracy: 0.9750 - loss: 0.0776
Epoch 3/5
1875/1875 - 5s - 2ms/step - accuracy: 0.9820 - loss: 0.0547
Epoch 4/5
1875/1875 - 5s - 3ms/step - accuracy: 0.9862 - loss: 0.0422
Epoch 5/5
1875/1875 - 5s - 3ms/step - accuracy: 0.9900 - loss: 0.0323
313/313 - 2s - 5ms/step - accuracy: 0.9764 - loss: 0.0910


[0.0910354033112526, 0.9764000177383423]

## Functional API
A bit more flexible

In [33]:
inputs = layers.Input(shape=(784, ))
x = layers.Dense(512, activation='relu', name="1_dense")(inputs)
x = layers.Dense(256, activation='relu', name='2_dense')(x)
outputs = layers.Dense(10, activation='softmax', name='3_out')(x)

model = keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())

Model: "functional_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_15 (InputLayer)     │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ 1_dense (Dense)                 │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ 2_dense (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ 3_out (Dense)                   │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

None


In [32]:
# Compile model: config cấu hình training cho model
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

In [35]:
model_debug = keras.Model(inputs = model.inputs,
                          outputs = [layer.output for layer in model.layers])

features = model_debug.predict(x_train)

for feature in features:
    print(feature.shape)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step
(60000, 784)
(60000, 512)
(60000, 256)
(60000, 10)


In [41]:
print(model.get_layer(name="1_dense").output)

<KerasTensor shape=(None, 512), dtype=float32, sparse=False, ragged=False, name=keras_tensor_43>
