<a href="https://colab.research.google.com/github/mducdaf2/tensorflow/blob/main/basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Basic of TensorFlow

In [1]:
import os
import tensorflow as tf

## Initialization Tensor

In [8]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)
print(type(x))
print(x.shape)
print(x.dtype)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(1, 1)
<dtype: 'float32'>


In [9]:
x = tf.constant([[1, 2, 3], [3, 4, 5]])
print(x)

tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)


`tf.ones()`

In [12]:
x = tf.ones((3, 3))
print(x)
print(type(x))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


`tf.eye()`

In [13]:
x = tf.eye(4)
print(x)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


`tf.random.normal()`

In [14]:
x = tf.random.normal((3, 4), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.6369526   0.03278659 -0.55777067  0.16458051]
 [-0.05639556 -1.7087642   0.54235435  1.0219183 ]
 [ 2.1836944   0.17501627  0.49634737  1.9849293 ]], shape=(3, 4), dtype=float32)


`tf.random.uniform()`

In [15]:
x = tf.random.uniform((1, 3), minval=0, maxval=3)
print(x)

tf.Tensor([[1.4095988 2.9160619 2.4031186]], shape=(1, 3), dtype=float32)


`tf.range()`

In [17]:
print(tf.range(1, 10, 2))

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


`tf.cast()`

In [24]:
x = tf.range(10)
print(x)
print(x.dtype)
y = tf.cast(x, dtype=tf.float16)
print(y)
print(y.dtype)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
<dtype: 'int32'>
tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float16)
<dtype: 'float16'>


## Mathematical Operations

In [30]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.tensordot(x, y, axes=0)
print(z)

tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)


In [40]:
print(tf.reduce_sum(z, axis=1))

tf.Tensor([24 48 72], shape=(3,), dtype=int32)


`tf.matmul()`

In [43]:
x = tf.random.normal((3, 4))
y = tf.random.normal((4, 5))
print(tf.matmul(x, y))
print(x @ y)

tf.Tensor(
[[ 3.9244134  -0.7617609   0.4639935   1.2898383   2.8519652 ]
 [ 2.5891833   2.1876554   0.13934976 -0.09681433 -1.0619564 ]
 [ 3.0821877  -0.36180305 -0.7070978   0.20272629  2.6380482 ]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[ 3.9244134  -0.7617609   0.4639935   1.2898383   2.8519652 ]
 [ 2.5891833   2.1876554   0.13934976 -0.09681433 -1.0619564 ]
 [ 3.0821877  -0.36180305 -0.7070978   0.20272629  2.6380482 ]], shape=(3, 5), dtype=float32)


## Indexing

In [45]:
x = tf.range(10)
print(x[:])
print(x[2:])
print(x[:4])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)


In [47]:
indices = tf.constant([1, 3])
y = tf.gather(x, indices)
print(y)

tf.Tensor([1 3], shape=(2,), dtype=int32)


In [58]:
x = tf.constant([
    [2, 3, 4],
    [1, 2, 3]
])

print(x[:, 1:2])

tf.Tensor(
[[3]
 [2]], shape=(2, 1), dtype=int32)


## Reshaping

`tf.reshape()`

In [62]:
x = tf.range(9)
print(x)
y = tf.reshape(x, shape=(3, 3))
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


`tf.transpose()`

In [64]:
z = tf.transpose(y, perm=[1, 0])
print(z)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
